data:
  batch_size: 64
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  drop_path: 0.25
  mixup: 0.8
  nb_classes: 1010
  cutmix: 1.0
  reprob: 0.25
  image_folder:  iNaturalist2019/
  num_workers: 64
  pin_mem: true
  root_path: /home/rtcalumby/adam/luciano/
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  resume_epoch: 0
logging:
  folder: /home/rtcalumby/adam/luciano/LifeCLEFPlant2022/logs/inaturalist2019
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: true
  model_name: vit_huge
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true 
optimization:
  ema:
  - 0.9
  - 0.999
  epochs: 50
  final_lr: 1.0e-07 # Default: 1e-6
  final_weight_decay: 0.4  
  ipe_scale: 1.0
  lr: 1.0e-03 #0.0007 # Default 0.0015 -> lr = base lr × batchsize / 256. (learning rate formula). /0.0007
  start_lr: 1.0e-03 #0.00001 # Default: 0.0002 
  warmup: 10
  weight_decay: 0.05
  label_smoothing: 0.1

# mae lr: 0.0026. 6.5e-4 (blr)